[suites.unit]
# Human title of the suite.
title = "Unit tests"

# Rust glob based paths (no directory recursion)
paths = ["foobar/*.rs"]

# Optional executable which will be invoked to expand additional paths.
# The expected output is an exit code of 0 with newline delimited paths (such as
# can be found by the `find` utility or `ls -1`.
path_bin = "find $PWD -name '*_test.rs'"

# Executable used to run the task. For example if you wanted to test that each
# file is executable.
executable = "test -x"

