# List of sub manifests to be loaded.
manifests = [
  "subdirectory/overlord.toml",
  "subdirectory2/overlord.toml"
]

# Optional groups of suites... obviously if there are no suites nothing can be
# run but there may be root overlord files which only contain sub manifests...
[[suites]]
group = "unit"

# Rust glob based paths (no directory recursion)
paths = ["foobar/*.rs"]

# Executable used to run the task. For example if you wanted to test that each
# file is executable.
executable = "test -x"
